### ISSUE TITLE
selscan_file_conversion crashing (pysam?)

### ISSUE THREAD

**Issue by josephvitti** [broadinstitute/cms#71]
I'm running into a new bug when I try to use selscan_file_conversion. I give e.g. the following command:

`(cms-env3) hw-uger-1003:/idi/sabeti-scratch/jvitti 14:17:50 1018 $ python /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion /idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/YRI-overlap-IRN_chr1.recode.vcf.gz /idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr1.txt YRI-overlap-IRN_chr1 /idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ 1`

and this is the output: 

> 2016-08-31 14:17:58,879 - cmd:112:main_argparse - INFO - software version: 5a22200, python version: 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> 2016-08-31 14:17:58,879 - cmd:115:main_argparse - INFO - command: /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion rescaleGeneticDistance=False chromosomeNum=1 ploidy=2 codingFunctionClassFile=None tmpDir=/tmp/2972228.1.interactive loglevel=DEBUG considerMultiAllelic=False filterPops=None genMap=/idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr1.txt includeLowQualAncestral=False outPrefix=YRI-overlap-IRN_chr1 outLocation=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ inputVCF=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/YRI-overlap-IRN_chr1.recode.vcf.gz tmpDirKeep=False endBp=None sampleMembershipFile=None filterSuperPops=None multiAllelicMergeFunction=OR startBp=0
> 2016-08-31 14:17:58,880 - cmd:127:main_argparse - DEBUG - using tempDir: /tmp/2972228.1.interactive/tmp-scans-selscan_file_conversion-mck2k3jq
> Traceback (most recent call last):
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(**commands**, **doc**)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 136, in main_selscan_file_conversion
>     multi_alleli_merge_function               = args.multiAllelicMergeFunction)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 101, in process_vcf_into_selscan_tped
>     processor = VCFReader(vcf_file)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/vcf_reader.py", line 31, in **init**
>     self.sample_names  = self.read_sample_names()
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/vcf_reader.py", line 93, in read_sample_names
>     headerRowString = self.sample_header_line()
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/vcf_reader.py", line 81, in sample_header_line
>     elem = headerIter.next()
> AttributeError: 'pysam.ctabix.GZIteratorHead' object has no attribute 'next'
> 
> I've tried cloning the repository de novo, and have re-created the input VCFs (including bgzip and tabix) a few times, and can't seem to resolve the problem. Could this be to do with pysam version? @tomkinsc can you provide any insight?

**Comment by tomkinsc** [comment]
Hmm...what does the VCF header look like? I'll take a look at it. You could also try creating a separate new conda environment with a different version of pysam to see if rolling back to an older version, say 0.8.4, helps.

``` shell
conda create -c bioconda -p /idi/sabeti-scratch/jvitti/pysamtestenv pysam==0.8.4
source activate /idi/sabeti-scratch/jvitti/pysamtestenv
# basic test of the failing call:
python -c 'import pysam; f = pysam.TabixFile("/path/to/some.vcf", parser=pysam.asVCF()); print(f.header.next())'
```

(and then `rm -r /idi/sabeti-scratch/jvitti/pysamtestenv` to remove the test env)

**Comment by tomkinsc** [comment]
I'm able to replicate the issue using 0.8.4.

**Comment by tomkinsc** [comment]
Maybe see if this fixes it?
https://github.com/broadinstitute/cms/pull/72
Not quite sure what changed to cause it to break now. Maybe something with the underlying conda-sourced ctabix.

**Comment by josephvitti** [comment]
Hmm, a new (separate?) error appears. After printing b'{headerline}' for all of the lines starting with #:

> Traceback (most recent call last):
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(**commands**, **doc**)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 136, in main_selscan_file_conversion
>     multi_alleli_merge_function               = args.multiAllelicMergeFunction)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 103, in process_vcf_into_selscan_tped
>     end_pos = processor.clens[str(chromosome_num)] if end_pos_bp is None else end_pos_bp
> KeyError: '1'

**Comment by tomkinsc** [comment]
Does this resolve it?
https://github.com/broadinstitute/cms/pull/73

**Comment by josephvitti** [comment]
My comments keep disappearing?
Unfortunately produces a few more downstream issues:

> (cms-env3) hw-uger-1004:~ 09:31:57 1003 $ python /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion /idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/YRI-overlap-IRN_chr1.recode.vcf.gz /idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr1.txt YRI-overlap-IRN_chr1 /idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ 1
> 2016-09-02 09:32:06,988 - cmd:112:main_argparse - INFO - software version: a37b6d9-dirty, python version: 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> 2016-09-02 09:32:06,989 - cmd:115:main_argparse - INFO - command: /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion startBp=0 includeLowQualAncestral=False outLocation=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ rescaleGeneticDistance=False filterSuperPops=None filterPops=None genMap=/idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr1.txt considerMultiAllelic=False chromosomeNum=1 outPrefix=YRI-overlap-IRN_chr1 codingFunctionClassFile=None loglevel=DEBUG tmpDir=/tmp/2985367.1.interactive inputVCF=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/YRI-overlap-IRN_chr1.recode.vcf.gz sampleMembershipFile=None endBp=None multiAllelicMergeFunction=OR tmpDirKeep=False ploidy=2
> 2016-09-02 09:32:06,990 - cmd:127:main_argparse - DEBUG - using tempDir: /tmp/2985367.1.interactive/tmp-scans-selscan_file_conversion-dh2a2s_h
> Traceback (most recent call last):
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(**commands**, **doc**)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 136, in main_selscan_file_conversion
>     multi_alleli_merge_function               = args.multiAllelicMergeFunction)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 101, in process_vcf_into_selscan_tped
>     processor = VCFReader(vcf_file)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/vcf_reader.py", line 32, in **init**
>     self.clens         = self.contig_lengths()
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/vcf_reader.py", line 38, in contig_lengths
>     if line.startswith('##contig=<ID=') and line.endswith('>'):
> TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by tomkinsc** [comment]
Ok. Rather than spot-fix things, I'll activate your conda environment on the cluster and try to work through errors until the command runs to completion. Stay tuned for a PR, but it may be a little while. I think these are Unicode-string errors related to Python(3?) and its interaction with ctabix.

**Comment by josephvitti** [comment]
Hmm, I thought the most recent update fixed this issue, but I'm still seeing some unexpected behavior:

`(cms-env3) hw-uger-1004:/idi/sabeti-scratch/jvitti 10:02:30 1141 $ python /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion /idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/MATCHED/MATCHED_YRI_chr22.recode.vcf.gz /idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr22.txt retry_MATCHED_YRI_chr22 /idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ 22`

```
2016-09-04 10:03:18,307 - cmd:112:main_argparse - INFO - software version: a37b6d9-dirty, python version: 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
2016-09-04 10:03:18,307 - cmd:115:main_argparse - INFO - command: /idi/sabeti-scratch/jvitti/cms/cms/scans.py selscan_file_conversion ploidy=2 multiAllelicMergeFunction=OR startBp=1 loglevel=DEBUG chromosomeNum=22 outPrefix=retry_MATCHED_YRI_chr22 endBp=None inputVCF=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/MATCHED/MATCHED_YRI_chr22.recode.vcf.gz includeLowQualAncestral=False outLocation=/idi/sabeti-scratch/jvitti/cms_venv/dry_run/tpeds/ tmpDir=/tmp/2997526.1.interactive tmpDirKeep=False codingFunctionClassFile=None sampleMembershipFile=None filterSuperPops=None genMap=/idi/sabeti-scratch/ilya/gsvn/Data/Ilya_Data/genmaps/hm2/genetic_map_GRCh37_chr22.txt considerMultiAllelic=False rescaleGeneticDistance=False filterPops=None
2016-09-04 10:03:18,308 - cmd:127:main_argparse - DEBUG - using tempDir: /tmp/2997526.1.interactive/tmp-scans-selscan_file_conversion-gxawhu49


```

> Traceback (most recent call last):
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 580, in <module>
>     util.cmd.main_argparse(**commands**, **doc**)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/util/cmd.py", line 130, in main_argparse
>     ret = args.func_main(args)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/scans.py", line 136, in main_selscan_file_conversion
>     multi_alleli_merge_function               = args.multiAllelicMergeFunction)
>   File "/idi/sabeti-scratch/jvitti/cms/cms/tools/selscan.py", line 222, in process_vcf_into_selscan_tped
>     genotypes_for_selected_samples = operator.itemgetter(*indices_of_matching_genotypes)(genos)
> IndexError: string index out of range

**Comment by tomkinsc** [comment]
It looks like the problem is that while most VCF lines looks like this:

`22       17739036        rs9605248       G       C       100     PASS    AA=G;AC=311;AN=946;SF=0,1       GT      1|1     1|1     0|0     1|0     0|0     0|0     1|1     0|0     0|1 0|1         0|0     0|1     1|1     1|1     0|0     0|0     0|0     1|0     0|0     1|1     0|1     0|1     1|1     1|0     0|1     0|0     0|1     1|1     0|0     0|1     0|0     0|1 0|0         1|0     0|1     0|1     1|0     0|0     0|0     0|1     0|1     0|1     0|1     1|1     0|1     1|0     0|0     1|1     0|0     1|0     0|1     1|0     0|0     1|0     0|1 0|0         0|0     1|0     0|0     1|0     1|1     1|0     1|0     0|1     1|0     0|0     0|0     1|1     0|0     1|1     0|0     0|1     0|0     1|0     0|0     1|1     0|1     1|0 1|0         0|0     0|1     0|0     0|1     1|0     0|0     1|0     1|0     0|1     0|0     0|0     0|0     1|1     1|0     0|1     0|0     0|1     0|1     0|0     0|0     0|1     1|0 0|1         0|0     0|1     1|1     1|0     0|0     0|0`

Problematic ones can occur in the same file:

`22       17739655        .       C       T       .       PASS    AA=C;AC=1;AN=154;SF=0   GT      .       .       .       .       .       .       .       .       .       .       .   ..          .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .   ..          .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .   ..          .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .   ..          .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .       .   .`

There are 17 such lines in that VCF file for chr22, `/idi/sabeti-scratch/jvitti/cms_venv/dry_run/vcfs/MATCHED/MATCHED_YRI_chr22.recode.vcf.gz`

The genotypes for the problematic row include periods, which means a call could not be made at the locus for a given sample, however in this case the representation violates the [VCF spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf) since there are no allele separators:

> For haploid calls, e.g. on Y, male nonpseudoautosomal X, or mitochondrion, only one allele value should be given; a triploid call might look like 0/0/1. If a call cannot be made for a sample at a given locus, ‘.’ should be specified for each missing allele in the GT field (for example ‘./.’ for a diploid genotype and ‘.’ for haploid genotype). [Where '/' means the genotype is unphased and '|' is phased]

 We assume that the genotype count at a given locus matches the number of samples*ploidy, and parsing failed when that assumption was violated by the problematic lines.

How do we want to handle such loci? It may be best to skip the problem lines and continue on, since they're both malformed and uninformative. Such a change is in https://github.com/broadinstitute/cms/pull/75. Lines that include correct ploidy for the unknowns should pass OK.

Edit: Out of curiosity, what generated the VCF file with the problematic lines? It may be worth opening an issue upstream to have the author correct the encoding.

**Comment by josephvitti** [comment]
Ah, I should have spent some more time with the VCF before assuming the issue was in vcf_parser -- I apologize! 

These were processed with VCFtools (apply coverage mask, populate ancestral allele, filter on sites shared by Iranian + 1000G datasets, filter by pop/chrom). I'm going to backtrack and figure out where in that process these wonky lines appeared.  

Edit: from what I can tell I was incorrectly calling VCFtools overlap function. Easy fix. Sorry for the trouble!
